attach:
  url:
    prefix: http://localhost:9081/static/
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.100:8848
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.8.100:3306/tarena_lbs_attach?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.8.100:8848
    use-as-config-center: false
    use-as-metadata-center: false
    id: nacos
  consumer:
    check: false