server:
  # 网关必须 19999
  port: 19999
spring:
  profiles:
    active: local
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        # 第一个路由 /passport/admin/login lbs-basic服务
        - id: lbs_basic_route
          uri: lb://lbs-basic
          predicates:
            - Path=/passport/**,/basic/**,/admin/basic/**
        # 第二个路由 lbs-article
        - id: lbs_article_route
          uri: lb://lbs-article
          predicates:
            - Path=/admin/content/**,/content/**
        - id: lbs_marketing_route
          uri: lb://lbs-marketing
          predicates:
            - Path=/admin/marketing/**,/marketing/**
      # CORS跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true
            maxAge: 3600