#开放本地环境local
spring:
  #stream
  cloud:
    stream:
      bindings:
        store-location-output:
          destination: store-location-destination
  profiles:
    active: local
  #springmvc 参数策略 2.6.13boot整合springmvc 需要配置的属性
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #在springboot配置yaml 指定静态文件的访问路径 D://static
  web:
    resources:
      # 静态文件存储地址
      static-locations: file:D:/static/
  #spring应用名称
  application:
    name: lbs-basic
server:
  port: 9000
#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
#dubbo
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
  protocol:
    name: dubbo
    #端口 只要确定没人占用 就可以使用 配置-1这个特殊值 dubbo进程会自动寻找从20880开始
    #没有被占用的端口 节省配置段鸥思考时间
    port: -1
  consumer:
    check: false





















