#开放本地环境local
spring:
  profiles:
    active: local
  #springmvc 参数策略 2.6.13boot整合springmvc 需要配置的属性
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #spring应用名称
  application:
    name: lbs-basic
server:
  port: 9000
#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
